import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]

[env]
TERM = "xterm-256color"

# To fix Neovim "Ctrl + /" does not work in Alacritty.
# Origin issue link: https://github.com/alacritty/alacitty/issues/7608#issuecomment-1975006973
[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGM Nerd Font Mono"
size = 14
